# 应用名称
spring:
  application:
    name: springboot-actuator

## 若要访问端点信息，需要配置用户名和密码
#  security:
#    user:
#      name: admin
#      password: 123456
##监控管理
management:
#  # 端点信息接口使用的端口，为了和主系统接口使用的端口进行分离
#  server:
#    port: 8090
#    servlet:
#  # 端点健康情况，默认值"never"，设置为"always"可以显示硬盘使用情况和线程情况
#  endpoint:
#    health:
#      show-details: always
#    #      端点自动缓存对不带任何参数的读取操作的响应
#    beans:
#      cache:
#        time-to-live: 10s
  # 设置端点暴露的哪些内容，默认["health","info"]，设置"*"代表暴露所有可访问的端点
  endpoints:
    web:
      exposure:
        include: '*'

service:
  name: lll