
spring:
  thymeleaf:
    prefix: classpath:/templates/ # 默认路径 index.html
    suffix: .html # 后缀
    # 模板格式
    mode: HTML5
    encoding: utf-8
    cache: false
    servlet:
      content-type: text/html




  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.example.springboot.thymeleaf.entity
  mapper-locations: classpath:mapper/*Mapper.xml
