# 应用名称
#spring.application.name=springboot-ehcache




#cache:
#   type: ehcache
 #  ehcache:
  #   config: classpath:app1_ehcache.xml
spring:
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
logging:
  level:
    com.example: debug