# 应用名称
#spring.application.name=netty-springboot
#添加依赖
#server:
#  port: 80

logging:
  level:
    root: debug

#https://segmentfault.com/a/1190000015309478
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true



netty:
  websocket:
    # Websocket服务端口
    port: 1024
    # 绑定的网卡
    ip: 0.0.0.0
    # 消息帧最大体积
    max-frame-size: 10240
    # URI路径
    path: /channel

